
alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER PORTAL IDENTIFIED BY Tomeisa1204

SELECT * FROM chatacters a 



alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER PORTAL IDENTIFIED BY Tomeisa1204

SELECT * FROM chatacters a 



INSERT INTO SESSION_WORLD() VALUES

CREATE TABLE SESSION_WORLD (
ID_SESSION NUMBER DEFAULT SESSION_WORLD_SEQ .Nextval,
NAME_SESSION VARCHAR(200)
)

CREATE SEQUENCE SESSION_WORLD_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;

