
alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER PORTAL IDENTIFIED BY Tomeisa1204

SELECT * FROM chatacters a 



alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER PORTAL IDENTIFIED BY Tomeisa1204

SELECT * FROM chatacters a 



INSERT INTO SESSION_WORLD(NAME_SESSION) VALUES('ISAH')

CREATE TABLE SESSION_WORLD (
ID_SESSION NUMBER PRIMARY KEY DEFAULT SESSION_WORLD_SEQ.Nextval(),
NAME_SESSION VARCHAR(200)
)

CREATE SEQUENCE SESSION_WORLD_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;



SELECT * FROM CHARACTERS WHERE CH_ACC = 'andrade01'


alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER PORTAL IDENTIFIED BY Tomeisa1204

SELECT * FROM chatacters a 



INSERT INTO SESSION_WORLD() VALUES

CREATE TABLE SESSION_WORLD (
ID NUMBER DEFAULT SESSION_WORLD_SEQ .Nextval,
ID_SESSION VARCHAR(100),
NAME_SESSION VARCHAR(200)
)

CREATE SEQUENCE SESSION_WORLD_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;

CREATE SEQUENCE CHARACTER_ID_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;

ALTER TABLE CHARACTERS
ADD CH_ID NUMBER DEFAULT CHARACTER_ID_SEQ.NEXTVAL
INSERT INTO SESSION_WORLD (ID_SESSION,NAME_SESSION) VALUES('SANDBOX01','SANDBOX 01')

INSERT INTO AUTH."CHARACTERS"
(CH_ID, CH_NAME, CH_ACC, CH_TYPE, CH_POSX, CH_POSY, CH_POSZ, CH_ROT, CH_ID_SESSION)
VALUES(0, 'GM ISA', 0, 'GOD', '44', '10.72', '0.3245959', '0', 'SANDBOX01');


SELECT CH_NAME,CH_ID_SESSION FROM CHARACTERS WHERE CH_ACC = 'andrade01'
