
--alter session set "_ORACLE_SCRIPT"=true; 
--grant unlimited tablespace to REEGORN;
--grant create session TO REEGORN;

CREATE SEQUENCE SESSION_WORLD_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;


CREATE TABLE SESSION_WORLD (
ID NUMBER DEFAULT SESSION_WORLD_SEQ .Nextval,
ID_SESSION VARCHAR(100),
NAME_SESSION VARCHAR(200)
)

INSERT INTO SESSION_WORLD(NAME_SESSION) VALUES('ISAH')

INSERT INTO SESSION_WORLD (ID_SESSION,NAME_SESSION) VALUES('SANDBOX01','SANDBOX 01')

CREATE SEQUENCE CHARACTER_ID_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;

CREATE TABLE REEGORN."CHARACTERS"(
	CH_NAME VARCHAR(100),
	CH_ACC VARCHAR(100),
	CH_TYPE VARCHAR(30),
	CH_POSX VARCHAR(10),
	CH_POSY VARCHAR(10),
	CH_POSZ VARCHAR(10),
	CH_ROT VARCHAR(10),
	CH_ID_SESSION VARCHAR(100)
)


ALTER TABLE REEGORN."CHARACTERS"
ADD CH_ID NUMBER DEFAULT CHARACTER_ID_SEQ.NEXTVAL


INSERT INTO REEGORN."CHARACTERS"
(CH_NAME, CH_ACC, CH_TYPE, CH_ID_SESSION, CH_ID, CH_HP, CH_GENDER, CH_LEVEL, CH_CLASS, CH_LOCAL, CH_WORLD, CH_POSX, CH_POSY, CH_POSZ, CH_ROT)
VALUES('GM ISA', 'andrade01', 'GOD', 'SANDBOX01', 0, 1000, 'MALE', 2752, 'GOD', 'SANDBOX01', '1', 44, 10.72, 0.3245959, 0);
INSERT INTO REEGORN."CHARACTERS"
(CH_NAME, CH_ACC, CH_TYPE, CH_ID_SESSION, CH_ID, CH_HP, CH_GENDER, CH_LEVEL, CH_CLASS, CH_LOCAL, CH_WORLD, CH_POSX, CH_POSY, CH_POSZ, CH_ROT)
VALUES('GM TOM', 'andrade01', 'GOD', 'SANDBOX01', 1, 1000, 'FEMALE', 7537, 'GOD', 'SANDBOX01', '1', 44, 10.72, 0.3245959, 0);



CREATE SEQUENCE ACCOUNTS_ID_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;

CREATE TABLE REEGORN."ACCOUNTS"(
	USER_NAME VARCHAR(100),
	ACCESS_KEY VARCHAR(100)
)

ALTER TABLE REEGORN."ACCOUNTS"
ADD ID NUMBER DEFAULT ACCOUNTS_ID_SEQ.NEXTVAL


CREATE SEQUENCE ROLES_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
nocache
cycle;


CREATE TABLE ROLES (
ID NUMBER DEFAULT ROLES_SEQ .Nextval,
NAME_ROLE VARCHAR(200),
ACCOUNT_ID VARCHAR(100)
)

INSERT INTO REEGORN."ACCOUNTS" (USER_NAME,ACCESS_KEY) VALUES ('andrade01','123456');
INSERT INTO REEGORN."ROLES" (ACCOUNT_ID,NAME_ROLE) VALUES ('1','SANDBOX01');

SELECT * FROM REEGORN."CHARACTERS" WHERE CH_ACC = 'andrade01';

SELECT * FROM ACCOUNTS;
